---
title: "Visualization"
subtitle: "Part II"
author: "AnMei Chen"
date: "10/5/2021"
output: github_document
---

```{r }
library(tidyverse)
library(patchwork)

```

## load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```


## Remember this plot ..?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
  
```

## labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  )
```


## Scales

start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  ) +
  #defining some scales:
  #for x axis
  scale_x_continuous(
    #define and label the breaks(needs to be numbers)
    breaks = c(-15,0,15),
    labels = c("-15 C","0","15")
  ) +
  #for y axis
  scale_y_continuous(
    #square root transformation
    #trans = "sqrt"
    #change the y axis labels to the right side
    position = "right"
  )
```

Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  ) +
  # Change the color of the points; by default it goes from 0 to 360
  scale_color_hue(
    #change the label:"name" of the points to "location"
    name = "Location",
    h = c(100,300))
```



```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  ) +
  #scale_color_viridis assume the value you enter is continuous
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE)
```

# Themes

shift the legend

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  ) +
  #scale_color_viridis assume the value you enter is continuous
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE) +
  theme(legend.position = "bottom")
```

change the overall theme

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperature in 2017."
  ) +
  #scale_color_viridis assume the value you enter is continuous
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE) +
  theme_minimal() +
  #theme_bw()
  #theme_classic()
  #ggthemes::theme_excel()
  theme(legend.position = "bottom")
```


## Setting options

Options to put at the very begining of the Rmarkdown document:
```{r evol = FALSE}
library(tidyverse)

# set figure width, aspect ratio and output width(shrunk down the figure to 90% instead of 100%) for all figures in this file 

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

# to determine a theme for the entire document
theme_set(theme_minimal() + theme(legend.position = "bottom"))

# update some options to override ggplots:
# make sure every plot that we use in this file use the cirtus color palette
options(
  ggplot2.continuous.colour = "viridis" , 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data args in `geom`

```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY") 

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

# to use one dataset on geom_point() and a diff dataset on geom_line()
ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```

## `patchwork`

remember faceting?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .5) +
  #create a multipanel plot with the exact same type of plot
  facet_grid((. ~ name))
```

what happens when you want multipanel plot but cant facet ...?

```{r}
tmax_tmin_p =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df %>%
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
  theme(legend.position =  "none")

tmax_date_p = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  #se = standard error
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")
  
# use patchwork to organzie diff. type of plots into a single figure, even with fundamentally diff geometries, mappings and arguments.

#tmax_tmin_p + prcp_dens_p + tmax_date_p
(tmax_tmin_p + prcp_dens_p) / tmax_date_p
```

